### ISSUE TITLE
Symmetric Matrices ?

### ISSUE THREAD

**Issue by joecomp** [liuyangzhuan/ButterflyPACK#4]
Dear developers

Is it possible to use a symmetric matrix and work  with the only upper or lower part of the symmetric matrix (Cholesky matrix) ?

Thanks in adavnce for your answer

Regards

**Comment by liuyangzhuan** [comment]
Currently we don't take advantages of symmetric matrices. But this can added as a feature in a future release.

**Comment by joecomp** [comment]
Thanks for your quick answer

I will follow your work to see if this feature will be implemented.

Have a great day.
